apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profolio-dev-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:CharlieParker/profolio.git
    targetRevision: main
    path: charts/postgres
    helm:
      releaseName: postgres
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: profolio-dev
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
